ci: lint checks

diff --git a/.github/workflows/reusable-build-test-release.yml b/.github/workflows/reusable-build-test-release.yml
--- a/.github/workflows/reusable-build-test-release.yml
+++ b/.github/workflows/reusable-build-test-release.yml
@@ -417,15 +417,20 @@ jobs:
       - name : Job summary
         run: |
           sudo apt-get install -y libxml2-utils
-          junit_xml_path="test-results/junit.xml"
-          total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
-          failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
-          errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
-          skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
-          passed=$((total_tests - failures - errors - skipped))
-
-          echo -e "| Total Tests | Passed Tests | Failed Tests | Errored Tests | Skipped Tests |\n| ----------- | ------------ | ------------ | ------------- | ------------- |\n| $total_tests | $passed | $failures | $errors | $skipped |" >> "$GITHUB_STEP_SUMMARY"
-
+          junit_xml_path="test-results/junit.xml"          
+          junit_xml_path="${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
+          junit_xml_file=$(find "$junit_xml_path" 2>/dev/null | head -n 1)
+          if [ -n "$junit_xml_file" ]; then
+              total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
+              failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
+              errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
+              skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
+              passed=$((total_tests - failures - errors - skipped))
+              echo -e "| Total Tests | Passed Tests | Failed Tests | Errored Tests | Skipped Tests |\n| ----------- | ------------ | ------------ | ------------- | ------------- |\n| $total_tests | $passed | $failures | $errors | $skipped |" >> "$GITHUB_STEP_SUMMARY"
+          else
+              echo "No XML files found, exiting"
+              exit 1
+          fi
       - uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
@@ -480,15 +485,20 @@ jobs:
       - name : Job summary
         run: |
           sudo apt-get install -y libxml2-utils
-          junit_xml_path="test-results/junit.xml"
-          total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
-          failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
-          errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
-          skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
-          passed=$((total_tests - failures - errors - skipped))
-          
-          echo -e "| Total Tests | Passed Tests | Failed Tests | Errored Tests | Skipped Tests |\n| ----------- | ------------ | ------------ | ------------- | ------------- |\n| $total_tests | $passed | $failures | $errors | $skipped |" >> "$GITHUB_STEP_SUMMARY"
-
+          junit_xml_path="test-results/junit.xml"          
+          junit_xml_path="${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
+          junit_xml_file=$(find "$junit_xml_path" 2>/dev/null | head -n 1)
+          if [ -n "$junit_xml_file" ]; then
+              total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
+              failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
+              errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
+              skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
+              passed=$((total_tests - failures - errors - skipped))
+              echo -e "| Total Tests | Passed Tests | Failed Tests | Errored Tests | Skipped Tests |\n| ----------- | ------------ | ------------ | ------------- | ------------- |\n| $total_tests | $passed | $failures | $errors | $skipped |" >> "$GITHUB_STEP_SUMMARY"
+          else
+              echo "No XML files found, exiting"
+              exit 1
+          fi
       - uses: actions/upload-artifact@v4
         if: success() || failure()
         with:
@@ -1220,13 +1230,18 @@ jobs:
         run: |
           apt-get install -y libxml2-utils
           junit_xml_path="${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
-          total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' $junit_xml_path)
-          failures=$(xmllint --xpath 'sum(//testsuite/@failures)' $junit_xml_path)
-          errors=$(xmllint --xpath 'sum(//testsuite/@errors)' $junit_xml_path)
-          skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' $junit_xml_path)
-          passed=$((total_tests - failures - errors - skipped))
-          
-          echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} |$total_tests |$passed |$failures |$errors | $skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          junit_xml_file=$(find "$junit_xml_path" 2>/dev/null | head -n 1)
+          if [ -n "$junit_xml_file" ]; then
+              total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_file")
+              failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_file")
+              errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_file")
+              skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_file")
+              passed=$((total_tests - failures - errors - skipped))
+              echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} |$total_tests |$passed |$failures |$errors | $skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          else
+              echo "No XML files found, exiting"
+              exit 1
+          fi
       - name: Upload-${{ matrix.splunk.version }}-${{ matrix.sc4s.version }}-${{ env.TEST_TYPE }}
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
@@ -1466,12 +1481,18 @@ jobs:
         run: |
           apt-get install -y libxml2-utils
           junit_xml_path="${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
-          total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
-          failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
-          errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
-          skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
-          passed=$((total_tests - failures - errors - skipped))
-          echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} |$total_tests |$passed |$failures |$errors |$skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          junit_xml_file=$(find "$junit_xml_path" 2>/dev/null | head -n 1)
+          if [ -n "$junit_xml_file" ]; then
+              total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_file")
+              failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_file")
+              errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_file")
+              skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_file")
+              passed=$((total_tests - failures - errors - skipped))
+              echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} |$total_tests |$passed |$failures |$errors |$skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          else
+              echo "No XML files found, exiting"
+              exit 1
+          fi
       - name: Upload-${{ matrix.splunk.version }}-${{ matrix.sc4s.version }}-${{ env.TEST_TYPE }}
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
@@ -1733,12 +1754,18 @@ jobs:
         run: |
           apt-get install -y libxml2-utils
           junit_xml_path="${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
-          total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
-          failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
-          errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
-          skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
-          passed=$((total_tests - failures - errors - skipped))
-          echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ matrix.browser }} ${{ matrix.vendor-version.image }} ${{ matrix.marker }} |$total_tests |$passed |$failures |$errors |$skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          junit_xml_file=$(find "$junit_xml_path" 2>/dev/null | head -n 1)
+          if [ -n "$junit_xml_file" ]; then
+              total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_file")
+              failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_file")
+              errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_file")
+              skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_file")
+              passed=$((total_tests - failures - errors - skipped))
+              echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ matrix.browser }} ${{ matrix.vendor-version.image }} ${{ matrix.marker }} |$total_tests |$passed |$failures |$errors |$skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          else
+              echo "No XML files found, exiting"
+              exit 1
+          fi
       - name: Upload-artifact-for-github-summary
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
@@ -1998,12 +2025,18 @@ jobs:
         run: |
           apt-get install -y libxml2-utils
           junit_xml_path="${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
-          total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
-          failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
-          errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
-          skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
-          passed=$((total_tests - failures - errors - skipped))
-          echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ matrix.marker }} ${{ matrix.vendor-version.image }} |$total_tests |$passed |$failures |$errors | $skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          junit_xml_file=$(find "$junit_xml_path" 2>/dev/null | head -n 1)
+          if [ -n "$junit_xml_file" ]; then
+              total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_file")
+              failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_file")
+              errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_file")
+              skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_file")
+              passed=$((total_tests - failures - errors - skipped))
+              echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ matrix.marker }} ${{ matrix.vendor-version.image }} |$total_tests |$passed |$failures |$errors | $skipped |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          else
+              echo "No XML files found, exiting"
+              exit 1
+          fi
       - name: Upload-artifact-for-github-summary
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
@@ -2260,12 +2293,18 @@ jobs:
         run: |
           apt-get install -y libxml2-utils
           junit_xml_path="${{ needs.setup.outputs.directory-path }}/test-results/*.xml"
-          total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_path")
-          failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_path")
-          errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_path")
-          skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_path")
-          passed=$((total_tests - failures - errors - skipped))
-          echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ matrix.vendor-version.image }} ${{ steps.os-name-version.outputs.os-name }} ${{ steps.os-name-version.outputs.os-version }} |$total_tests |$passed |$failures |$errors |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          junit_xml_file=$(find "$junit_xml_path" 2>/dev/null | head -n 1)
+          if [ -n "$junit_xml_file" ]; then
+              total_tests=$(xmllint --xpath 'sum(//testsuite/@tests)' "$junit_xml_file")
+              failures=$(xmllint --xpath 'sum(//testsuite/@failures)' "$junit_xml_file")
+              errors=$(xmllint --xpath 'sum(//testsuite/@errors)' "$junit_xml_file")
+              skipped=$(xmllint --xpath 'sum(//testsuite/@skipped)' "$junit_xml_file")
+              passed=$((total_tests - failures - errors - skipped))
+              echo "splunk ${{ matrix.splunk.version }}${{ secrets.OTHER_TA_REQUIRED_CONFIGS }} ${{ matrix.vendor-version.image }} ${{ steps.os-name-version.outputs.os-name }} ${{ steps.os-name-version.outputs.os-version }} |$total_tests |$passed |$failures |$errors |${{steps.test_report.outputs.url_html}}" > job_summary.txt
+          else
+              echo "No XML files found, exiting"
+              exit 1
+          fi
       - name: Upload-${{ matrix.splunk.version }}-${{ matrix.sc4s.version }}-${{ env.TEST_TYPE }}
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
